---
name: pre-commit Updater

on:
  schedule:
    - cron: "0 9 * * 1-5" # Monday-Friday at 09:00 UTC
  workflow_dispatch:

permissions: {}

jobs:
  pre-commit-updater:
    name: pre-commit Updater
    permissions:
      contents: write
      pull-requests: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/pre-commit-updater.yml@b07b9612eebe68b8f5fce1b959b4f8555a6f67ea # v2.4.0
