---
name: Spell Check

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  spell-check:
    name: Spell Check
    permissions:
      contents: read
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/spell-check.yml@6df010e45fdb953369f12ab2bc69107d3c487f15 # v4.0.8
