---
name: Zizmor

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  zizmor:
    name: Zizmor
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/zizmor.yml@6df010e45fdb953369f12ab2bc69107d3c487f15 # v4.0.8
